import turtle
turtle.bgcolor('wheat')

turtle.speed(10)
str = "此生无悔入华夏\n来世还做中国人"
turtle.setup(1800,700,70,70)
turtle.color('black', 'pink')
turtle.pensize(3)  
turtle.hideturtle() 
turtle.up() 
turtle.goto(-255, -255)
turtle.down()
turtle.showturtle()
#画左边的小人
turtle.goto(-200,-200)
turtle.goto(-200,-120)
turtle.circle(35)
turtle.goto(-200,-200)
turtle.forward(40)
turtle.right(90)
turtle.forward(60)
turtle.hideturtle()
turtle.up() 
turtle.goto(-200, -160)
turtle.down()
turtle.showturtle()
turtle.left(90)
turtle.forward(55)
turtle.right(45)
turtle.forward(20)
turtle.hideturtle()
turtle.up()
turtle.goto(-200, -145)
turtle.down()
turtle.showturtle()
turtle.goto(-145, -145)
turtle.left(90)
turtle.forward(20)

#画第一个爱心
turtle.color('pink', 'pink')
turtle.begin_fill()
turtle.hideturtle()
turtle.up()
turtle.goto(-100, -153)
turtle.down()
turtle.showturtle()
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(45)
turtle.circle(10.6,180)
turtle.left(180)
turtle.circle(10.6,180)
turtle.end_fill()
#下一个大爱心
turtle.color('pink', 'pink')
turtle.begin_fill()
turtle.hideturtle()
turtle.up()
turtle.goto(-30, -143)
turtle.down()
turtle.showturtle()
turtle.left(135)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(45)
turtle.circle(17.67,180)
turtle.left(180)
turtle.circle(17.67,180)
turtle.end_fill()

#第三个爱心
turtle.color('pink', 'pink')
turtle.begin_fill()
turtle.hideturtle()
turtle.up()
turtle.goto(65, -133)
turtle.down()
turtle.showturtle()
turtle.left(135)
turtle.right(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(70)
turtle.left(45)
turtle.circle(24.74,180)
turtle.left(180)
turtle.circle(24.74,180)
turtle.end_fill()

#第四个爱心
turtle.color('pink', 'pink')
turtle.begin_fill()
turtle.hideturtle()
turtle.up()
turtle.goto(187, -133)
turtle.down()
turtle.showturtle()
turtle.left(135)
turtle.right(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(70)
turtle.left(45)
turtle.circle(24.74,180)
turtle.left(180)
turtle.circle(24.74,180)
turtle.end_fill()

#第5个爱心
turtle.color('pink', 'pink')
turtle.begin_fill()
turtle.hideturtle()
turtle.up()
turtle.goto(313.7, -143)
turtle.down()
turtle.showturtle()
turtle.left(135)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(45)
turtle.circle(17.67,180)
turtle.left(180)
turtle.circle(17.67,180)
turtle.end_fill()

#第6个爱心
turtle.color('pink', 'pink')
turtle.begin_fill()
turtle.hideturtle()
turtle.up()
turtle.goto(420, -153)
turtle.down()
turtle.showturtle()
turtle.right(90)
turtle.right(225)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.left(45)
turtle.circle(10.6,180)
turtle.left(180)
turtle.circle(10.6,180)
turtle.end_fill()

#画右边的小人
turtle.hideturtle()
turtle.color('dimgray')
turtle.up()
turtle.goto(651.28, -255)
turtle.down()
turtle.showturtle()
turtle.goto(550,-200)
turtle.goto(550,-120)
turtle.left(90)
turtle.circle(35)
turtle.goto(550,-200)
turtle.left(180)
turtle.forward(40)
turtle.left(90)
turtle.forward(60)
turtle.hideturtle()
turtle.up()
turtle.goto(550,-160)
turtle.down() 
turtle.showturtle()
turtle.right(90)
turtle.forward(55)
turtle.left(45)
turtle.forward(20)
turtle.hideturtle()
turtle.up() 
turtle.goto(550, -145)
turtle.down()
turtle.showturtle()
turtle.right(45)
turtle.forward(55)
turtle.right(45)
turtle.forward(20)

#画气球线和气球
#第一个气球
turtle.color('pink')
turtle.hideturtle()
turtle.up()
turtle.goto(235, -133)
turtle.down()
turtle.showturtle()
turtle.goto(245, 0)
turtle.right(135)
turtle.circle(35)
#第2个气球
turtle.hideturtle()
turtle.up()
turtle.goto(235, -133)
turtle.down()
turtle.showturtle()
turtle.goto(105, 80)
turtle.circle(40)
#第3个气球
turtle.hideturtle()
turtle.up()
turtle.goto(347, -133)
turtle.down()
turtle.showturtle()
turtle.goto(367, 0)
turtle.circle(35)
#第4一个气球
turtle.hideturtle()
turtle.up()
turtle.goto(337, -133)
turtle.down()
turtle.showturtle()
turtle.goto(317, 80)
turtle.circle(40)
#写字LOVE
turtle.pencolor("GREEN")
turtle.penup()
turtle.goto(245,10)
turtle.write("O",move=False,align='center',font=("微软雅黑",30,'normal'))


turtle.pencolor("PURPLE")
turtle.penup()
turtle.goto(105,90)
turtle.write("L",move=False,align='center',font=("微软雅黑",30,'normal'))

turtle.pencolor("YELLOW")
turtle.penup()
turtle.goto(367,10)
turtle.write("E",move=False,align='center',font=("微软雅黑",30,'normal'))

turtle.pencolor("ORANGE")
turtle.penup()
turtle.goto(317, 90)
turtle.write("V",move=False,align='center',font=("微软雅黑",30,'normal'))

turtle.pencolor("indianred")
turtle.penup()
turtle.goto(220, -300)
turtle.write(str,move=False,align='center',font=("微软雅黑",25,'normal'))

turtle.up()
turtle.goto(-600,300)
turtle.down()
turtle.fillcolor("grey")
turtle.pencolor("grey")
turtle.right(90)
turtle.pensize(8)
turtle.forward(600)

turtle.begin_fill()
turtle.fillcolor("silver")
turtle.pensize(1)
turtle.right(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(224)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(80)
turtle.end_fill()

turtle.pensize(1)
turtle.right(90)
turtle.forward(400)
turtle.right(90)

# 党旗
turtle.fillcolor("red")
turtle.pencolor("red")
turtle.up()
turtle.goto(-600, 300)
turtle.down()
turtle.begin_fill()
for i in range(2):
    turtle.forward(450)
    turtle.right(90)
    turtle.forward(300)
    turtle.right(90)
turtle.end_fill()
# 党徽
turtle.fillcolor("yellow")
turtle.pencolor("yellow")
turtle.up()
turtle.goto(-370, 240)
turtle.seth(225)
turtle.down()
turtle.begin_fill()
turtle.fd(125)
turtle.right(90)
turtle.fd(50)
turtle.right(90)
turtle.fd(100)
turtle.right(90)
turtle.circle(25, 90)
turtle.end_fill()
turtle.up()
turtle.goto(-420, 210)
turtle.seth(-45)
turtle.down()
turtle.begin_fill()
for i in range(2):
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
turtle.end_fill()
turtle.up()
turtle.goto(-480, 120)
turtle.seth(-50)
turtle.down()
turtle.begin_fill()
turtle.circle(100, 180)
turtle.fd(20)
turtle.right(157)
turtle.circle(-115, 190)
turtle.left(90)
turtle.fd(20)
turtle.right(90)
turtle.fd(20)
turtle.right(90)
turtle.fd(20)
turtle.left(80)
turtle.fd(30)
turtle.end_fill()
turtle.up()
turtle.goto(-470, 70)
turtle.down()
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

turtle.pencolor("black")

turtle.color("orangered")

turtle.up()
turtle.goto(-20,230)
turtle.down()
turtle.write("庆祝中国共产党成立100周年！",font = ("Times", 40, "bold"))

turtle.hideturtle()
turtle.done()




